import { getToolRegistry } from './ToolRegistry';
import { KnowledgeBaseSearchTool } from './KnowledgeBaseSearchTool';
import { ChatSummariesSearchTool } from './ChatSummariesSearchTool';
import { ChatMessagesSearchTool } from './ChatMessagesSearchTool';
import { KnowledgeBaseCountTool } from './KnowledgeBaseCountTool';
import { ChatSummariesCountTool } from './ChatSummariesCountTool';
import { KnowledgeBaseCreatePageTool } from './KnowledgeBaseCreatePageTool';
import { KnowledgeBaseUpdatePageTool } from './KnowledgeBaseUpdatePageTool';
import { KnowledgeBaseDeletePageTool } from './KnowledgeBaseDeletePageTool';
import { KnowledgeBaseListPagesTool } from './KnowledgeBaseListPagesTool';
import { KnowledgeBaseGetPageTool } from './KnowledgeBaseGetPageTool';
import { KubectlListPodsTool } from './KubectlListPodsTool';
import { KubectlListNodesTool } from './KubectlListNodesTool';
import { KubectlDescribePodTool } from './KubectlDescribePodTool';
import { KubectlLogsTool } from './KubectlLogsTool';
import { KubectlGetEventsTool } from './KubectlGetEventsTool';
import { KubectlTopNodesTool } from './KubectlTopNodesTool';
import { KubectlTopPodsTool } from './KubectlTopPodsTool';
import { KubectlGetDeploymentsTool } from './KubectlGetDeploymentsTool';
import { KubectlRolloutStatusTool } from './KubectlRolloutStatusTool';
import { KubectlRolloutRestartTool } from './KubectlRolloutRestartTool';
import { KubectlGetServicesTool } from './KubectlGetServicesTool';
import { KubectlGetIngressesTool } from './KubectlGetIngressesTool';
import { KubectlApplyDryRunTool } from './KubectlApplyDryRunTool';
import { KubectlApplyTool } from './KubectlApplyTool';
import { LimaListInstancesTool } from './LimaListInstancesTool';
import { LimaInstanceStatusTool } from './LimaInstanceStatusTool';
import { LimaShellTool } from './LimaShellTool';
import { AgentGetSettingsTool } from './AgentGetSettingsTool';
import { AgentUpdateSettingsTool } from './AgentUpdateSettingsTool';
import { KubectlExecTool } from './KubectlExecTool';
import { KubectlCpFromPodTool } from './KubectlCpFromPodTool';
import { KubectlCpToPodTool } from './KubectlCpToPodTool';
import { KubectlGetPodYamlTool } from './KubectlGetPodYamlTool';
import { KubectlGetPodStatusTool } from './KubectlGetPodStatusTool';
import { HostListDirTool } from './HostListDirTool';
import { HostReadFileTool } from './HostReadFileTool';
import { HostTailFileTool } from './HostTailFileTool';
import { HostStatTool } from './HostStatTool';
import { HostFindFilesTool } from './HostFindFilesTool';
import { HostGrepTool } from './HostGrepTool';
import { HostRunCommandTool } from './HostRunCommandTool';
import { HostImageMetadataTool } from './HostImageMetadataTool';
import { EmitChatMessageTool } from './EmitChatMessageTool';
import { EmitChatImageTool } from './EmitChatImageTool';
import { CalendarListEventsTool } from './CalendarListEventsTool';
import { CalendarGetNextEventTool } from './CalendarGetNextEventTool';
import { CalendarGetEventTool } from './CalendarGetEventTool';
import { CalendarCreateEventTool } from './CalendarCreateEventTool';
import { CalendarUpdateEventTool } from './CalendarUpdateEventTool';
import { CalendarDeleteEventTool } from './CalendarDeleteEventTool';
import { SkillRunPluginTool } from './SkillRunPluginTool';
import { SkillListTool } from './SkillListTool';
import { SkillListEnabledTool } from './SkillListEnabledTool';
import { SkillInstallTool } from './SkillInstallTool';
import { SkillEnableTool } from './SkillEnableTool';
import { SkillDisableTool } from './SkillDisableTool';
import { ToolListTool } from './ToolListTool';

let registered = false;

export function registerDefaultTools(): void {
  if (registered) {
    return;
  }

  const registry = getToolRegistry();
  registry.register(new KnowledgeBaseSearchTool());
  registry.register(new ChatSummariesSearchTool());
  registry.register(new ChatMessagesSearchTool());
  registry.register(new KnowledgeBaseCountTool());
  registry.register(new ChatSummariesCountTool());
  registry.register(new KnowledgeBaseCreatePageTool());
  registry.register(new KnowledgeBaseUpdatePageTool());
  registry.register(new KnowledgeBaseDeletePageTool());
  registry.register(new KnowledgeBaseListPagesTool());
  registry.register(new KnowledgeBaseGetPageTool());
  registry.register(new KubectlListPodsTool());
  registry.register(new KubectlListNodesTool());
  registry.register(new KubectlDescribePodTool());
  registry.register(new KubectlLogsTool());
  registry.register(new KubectlGetEventsTool());
  registry.register(new KubectlTopNodesTool());
  registry.register(new KubectlTopPodsTool());
  registry.register(new KubectlGetDeploymentsTool());
  registry.register(new KubectlRolloutStatusTool());
  registry.register(new KubectlRolloutRestartTool());
  registry.register(new KubectlGetServicesTool());
  registry.register(new KubectlGetIngressesTool());
  registry.register(new KubectlApplyDryRunTool());
  registry.register(new KubectlApplyTool());
  registry.register(new LimaListInstancesTool());
  registry.register(new LimaInstanceStatusTool());
  registry.register(new LimaShellTool());
  registry.register(new AgentGetSettingsTool());
  registry.register(new AgentUpdateSettingsTool());
  registry.register(new KubectlExecTool());
  registry.register(new KubectlCpFromPodTool());
  registry.register(new KubectlCpToPodTool());
  registry.register(new KubectlGetPodYamlTool());
  registry.register(new KubectlGetPodStatusTool());
  registry.register(new HostListDirTool());
  registry.register(new HostReadFileTool());
  registry.register(new HostTailFileTool());
  registry.register(new HostStatTool());
  registry.register(new HostFindFilesTool());
  registry.register(new HostGrepTool());
  registry.register(new HostRunCommandTool());
  registry.register(new HostImageMetadataTool());
  registry.register(new ToolListTool());
  registry.register(new SkillListTool());
  registry.register(new SkillListEnabledTool());
  registry.register(new SkillInstallTool());
  registry.register(new SkillEnableTool());
  registry.register(new SkillDisableTool());
  registry.register(new SkillRunPluginTool());
  registry.register(new EmitChatMessageTool());
  registry.register(new EmitChatImageTool());
  registry.register(new CalendarListEventsTool());
  registry.register(new CalendarGetNextEventTool());
  registry.register(new CalendarGetEventTool());
  registry.register(new CalendarCreateEventTool());
  registry.register(new CalendarUpdateEventTool());
  registry.register(new CalendarDeleteEventTool());
  registered = true;
}

export { getToolRegistry } from './ToolRegistry';
export { BaseTool } from './BaseTool';
export { KnowledgeBaseSearchTool } from './KnowledgeBaseSearchTool';
export { ChatSummariesSearchTool } from './ChatSummariesSearchTool';
export { ChatMessagesSearchTool } from './ChatMessagesSearchTool';
export { KnowledgeBaseCountTool } from './KnowledgeBaseCountTool';
export { ChatSummariesCountTool } from './ChatSummariesCountTool';
export { KnowledgeBaseCreatePageTool } from './KnowledgeBaseCreatePageTool';
export { KnowledgeBaseUpdatePageTool } from './KnowledgeBaseUpdatePageTool';
export { KnowledgeBaseDeletePageTool } from './KnowledgeBaseDeletePageTool';
export { KnowledgeBaseListPagesTool } from './KnowledgeBaseListPagesTool';
export { KnowledgeBaseGetPageTool } from './KnowledgeBaseGetPageTool';
export { KubectlListPodsTool } from './KubectlListPodsTool';
export { KubectlListNodesTool } from './KubectlListNodesTool';
export { KubectlDescribePodTool } from './KubectlDescribePodTool';
export { KubectlLogsTool } from './KubectlLogsTool';
export { KubectlGetEventsTool } from './KubectlGetEventsTool';
export { KubectlTopNodesTool } from './KubectlTopNodesTool';
export { KubectlTopPodsTool } from './KubectlTopPodsTool';
export { KubectlGetDeploymentsTool } from './KubectlGetDeploymentsTool';
export { KubectlRolloutStatusTool } from './KubectlRolloutStatusTool';
export { KubectlRolloutRestartTool } from './KubectlRolloutRestartTool';
export { KubectlGetServicesTool } from './KubectlGetServicesTool';
export { KubectlGetIngressesTool } from './KubectlGetIngressesTool';
export { KubectlApplyDryRunTool } from './KubectlApplyDryRunTool';
export { KubectlApplyTool } from './KubectlApplyTool';
export { LimaListInstancesTool } from './LimaListInstancesTool';
export { LimaInstanceStatusTool } from './LimaInstanceStatusTool';
export { LimaShellTool } from './LimaShellTool';
export { AgentGetSettingsTool } from './AgentGetSettingsTool';
export { AgentUpdateSettingsTool } from './AgentUpdateSettingsTool';
export { KubectlExecTool } from './KubectlExecTool';
export { KubectlCpFromPodTool } from './KubectlCpFromPodTool';
export { KubectlCpToPodTool } from './KubectlCpToPodTool';
export { KubectlGetPodYamlTool } from './KubectlGetPodYamlTool';
export { KubectlGetPodStatusTool } from './KubectlGetPodStatusTool';
export { HostListDirTool } from './HostListDirTool';
export { HostReadFileTool } from './HostReadFileTool';
export { HostTailFileTool } from './HostTailFileTool';
export { HostStatTool } from './HostStatTool';
export { HostFindFilesTool } from './HostFindFilesTool';
export { HostGrepTool } from './HostGrepTool';
export { HostRunCommandTool } from './HostRunCommandTool';
export { CalendarListEventsTool } from './CalendarListEventsTool';
export { CalendarGetNextEventTool } from './CalendarGetNextEventTool';
export { CalendarGetEventTool } from './CalendarGetEventTool';
export { CalendarCreateEventTool } from './CalendarCreateEventTool';
export { CalendarUpdateEventTool } from './CalendarUpdateEventTool';
export { CalendarDeleteEventTool } from './CalendarDeleteEventTool';
