import type { ToolManifest } from '../registry';

export const githubToolManifests: ToolManifest[] = [
  {
    name: 'github_add_remote',
    description: 'Add a remote repository to an existing git repository.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository" },
    remoteName: { type: 'string', description: "Name of the remote (usually 'origin')" },
    remoteUrl: { type: 'string', description: "URL of the remote repository" },
  },
    operationTypes: ['create'],
    loader: () => import('./github_add_remote'),
  },
  {
    name: 'github_comment_on_issue',
    description: 'Add a comment to a GitHub issue.',
    category: 'github',
    schemaDef: {
    owner: { type: 'string', description: "Repository owner (username or organization)" },
    repo: { type: 'string', description: "Repository name" },
    issue_number: { type: 'number', description: "Issue number" },
    body: { type: 'string', description: "Comment body" },
  },
    operationTypes: ['execute', 'create'],
    loader: () => import('./github_comment_on_issue'),
  },
  {
    name: 'github_create_file',
    description: 'Create a new file in a GitHub repository.',
    category: 'github',
    schemaDef: {
    owner: { type: 'string', description: "Repository owner (username or organization)" },
    repo: { type: 'string', description: "Repository name" },
    path: { type: 'string', description: "Path where the file should be created" },
    content: { type: 'string', description: "Content of the file" },
    message: { type: 'string', description: "Commit message" },
    branch: { type: 'string', optional: true, description: "Branch to create the file on" },
  },
    operationTypes: ['create'],
    loader: () => import('./github_create_file'),
  },
  {
    name: 'github_get_issue',
    description: 'Get details of a specific GitHub issue.',
    category: 'github',
    schemaDef: {
    owner: { type: 'string', description: "Repository owner (username or organization)" },
    repo: { type: 'string', description: "Repository name" },
    issue_number: { type: 'number', description: "Issue number" },
  },
    operationTypes: ['read'],
    loader: () => import('./github_get_issue'),
  },
  {
    name: 'github_get_issues',
    description: 'Get issues from a GitHub repository.',
    category: 'github',
    schemaDef: {
    owner: { type: 'string', description: "Repository owner (username or organization)" },
    repo: { type: 'string', description: "Repository name" },
    state: { type: 'enum', enum: ['open', 'closed', 'all'], default: 'open', description: "Issue state filter" },
    labels: { type: 'array', items: { type: 'string' }, optional: true, description: "Labels to filter issues" },
    since: { type: 'string', optional: true, description: "Only issues updated after this ISO 8601 timestamp" },
    limit: { type: 'number', optional: true, default: 10, description: "Maximum number of issues to return" },
  },
    operationTypes: ['read'],
    loader: () => import('./github_get_issues'),
  },
  {
    name: 'github_init',
    description: 'Initialize a git repository at the specified absolute path.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path where the git repository should be initialized" },
  },
    operationTypes: ['execute', 'create'],
    loader: () => import('./github_init'),
  },
  {
    name: 'github_list_branches',
    description: 'List branches in a GitHub repository.',
    category: 'github',
    schemaDef: {
    owner: { type: 'string', description: "Repository owner (username or organization)" },
    repo: { type: 'string', description: "Repository name" },
    protected: { type: 'boolean', optional: true, description: "Filter for protected branches only" },
  },
    operationTypes: ['read'],
    loader: () => import('./github_list_branches'),
  },
  {
    name: 'github_read_file',
    description: 'Read the contents of a file from a GitHub repository.',
    category: 'github',
    schemaDef: {
    owner: { type: 'string', description: "Repository owner (username or organization)" },
    repo: { type: 'string', description: "Repository name" },
    path: { type: 'string', description: "Path to the file in the repository" },
    ref: { type: 'string', optional: true, description: "Branch, tag, or commit SHA" },
  },
    operationTypes: ['read'],
    loader: () => import('./github_read_file'),
  },
  {
    name: 'git_blame',
    description: 'Show who last modified each line of a file. Optionally limit to a line range.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the file to blame" },
    startLine: { type: 'number', optional: true, description: "Start line number (1-indexed)" },
    endLine: { type: 'number', optional: true, description: "End line number (1-indexed)" },
  },
    operationTypes: ['read'],
    loader: () => import('./git_blame'),
  },
  {
    name: 'git_pull',
    description: 'Pull commits from a remote repository. Automatically reports any merge conflicts after pull.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
    remote: { type: 'string', optional: true, description: "Remote name (defaults to 'origin')" },
    branch: { type: 'string', optional: true, description: "Branch to pull (defaults to current branch)" },
  },
    operationTypes: ['execute'],
    loader: () => import('./git_pull'),
  },
  {
    name: 'git_conflicts',
    description: 'List files with merge conflicts and show the conflict diffs for each file.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
  },
    operationTypes: ['read'],
    loader: () => import('./git_conflicts'),
  },
  {
    name: 'git_add',
    description: 'Stage files for commit. If no files are specified, stages all changes.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
    files: { type: 'array', items: { type: 'string' }, optional: true, description: "Absolute file paths to stage. If omitted, stages all changes." },
  },
    operationTypes: ['execute'],
    loader: () => import('./git_add'),
  },
  {
    name: 'git_commit',
    description: 'Stage files and create a git commit. If no files are specified, stages all changes.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
    message: { type: 'string', description: "Commit message" },
    files: { type: 'array', items: { type: 'string' }, optional: true, description: "Absolute file paths to stage. If omitted, stages all changes." },
  },
    operationTypes: ['execute', 'create'],
    loader: () => import('./git_commit'),
  },
  {
    name: 'git_push',
    description: 'Push commits to a remote repository.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
    remote: { type: 'string', optional: true, description: "Remote name (defaults to 'origin')" },
    branch: { type: 'string', optional: true, description: "Branch to push (defaults to current branch)" },
  },
    operationTypes: ['execute'],
    loader: () => import('./git_push'),
  },
  {
    name: 'github_create_issue',
    description: 'Create a new issue in a GitHub repository.',
    category: 'github',
    schemaDef: {
    owner: { type: 'string', description: "Repository owner (username or organization)" },
    repo: { type: 'string', description: "Repository name" },
    title: { type: 'string', description: "Issue title" },
    body: { type: 'string', optional: true, description: "Issue body/description (markdown supported)" },
    labels: { type: 'array', items: { type: 'string' }, optional: true, description: "Labels to apply to the issue" },
    assignees: { type: 'array', items: { type: 'string' }, optional: true, description: "GitHub usernames to assign" },
  },
    operationTypes: ['create'],
    loader: () => import('./github_create_issue'),
  },
  {
    name: 'github_update_issue',
    description: 'Update an existing GitHub issue — edit title, body, labels, assignees, or state.',
    category: 'github',
    schemaDef: {
    owner: { type: 'string', description: "Repository owner (username or organization)" },
    repo: { type: 'string', description: "Repository name" },
    issue_number: { type: 'number', description: "Issue number" },
    title: { type: 'string', optional: true, description: "New title" },
    body: { type: 'string', optional: true, description: "New body" },
    state: { type: 'enum', enum: ['open', 'closed'], optional: true, description: "Set issue state" },
    labels: { type: 'array', items: { type: 'string' }, optional: true, description: "Replace labels" },
    assignees: { type: 'array', items: { type: 'string' }, optional: true, description: "Replace assignees" },
  },
    operationTypes: ['execute'],
    loader: () => import('./github_update_issue'),
  },
  {
    name: 'github_close_issue',
    description: 'Close a GitHub issue with an optional reason (completed or not_planned).',
    category: 'github',
    schemaDef: {
    owner: { type: 'string', description: "Repository owner (username or organization)" },
    repo: { type: 'string', description: "Repository name" },
    issue_number: { type: 'number', description: "Issue number" },
    reason: { type: 'enum', enum: ['completed', 'not_planned'], optional: true, description: "Close reason (defaults to 'completed')" },
  },
    operationTypes: ['execute'],
    loader: () => import('./github_close_issue'),
  },
  {
    name: 'github_create_pr',
    description: 'Create a pull request in a GitHub repository.',
    category: 'github',
    schemaDef: {
    owner: { type: 'string', description: "Repository owner (username or organization)" },
    repo: { type: 'string', description: "Repository name" },
    title: { type: 'string', description: "Pull request title" },
    head: { type: 'string', description: "Branch containing your changes" },
    base: { type: 'string', optional: true, description: "Branch to merge into (defaults to 'main')" },
    body: { type: 'string', optional: true, description: "Pull request description (markdown supported)" },
    draft: { type: 'boolean', optional: true, description: "Create as a draft PR" },
  },
    operationTypes: ['create'],
    loader: () => import('./github_create_pr'),
  },
  {
    name: 'git_branch',
    description: 'Create, switch, delete, or list git branches.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
    action: { type: 'enum', enum: ['list', 'create', 'switch', 'delete'], description: "Branch action to perform" },
    branchName: { type: 'string', optional: true, description: "Branch name (required for create, switch, delete)" },
  },
    operationTypes: ['execute'],
    loader: () => import('./git_branch'),
  },
  {
    name: 'git_status',
    description: 'Show the working tree status — current branch, staged/unstaged/untracked files.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
  },
    operationTypes: ['read'],
    loader: () => import('./git_status'),
  },
  {
    name: 'git_log',
    description: 'Show commit history for a repository.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
    limit: { type: 'number', optional: true, description: "Number of commits to show (defaults to 20)" },
    oneline: { type: 'boolean', optional: true, description: "One-line format (defaults to true)" },
  },
    operationTypes: ['read'],
    loader: () => import('./git_log'),
  },
  {
    name: 'git_diff',
    description: 'Show changes between working tree, staging area, or commits.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
    staged: { type: 'boolean', optional: true, description: "Show staged (cached) changes only" },
    commitA: { type: 'string', optional: true, description: "First commit SHA for comparison" },
    commitB: { type: 'string', optional: true, description: "Second commit SHA for comparison" },
    filePath: { type: 'string', optional: true, description: "Limit diff to a specific file path" },
  },
    operationTypes: ['read'],
    loader: () => import('./git_diff'),
  },
  {
    name: 'git_stash',
    description: 'Save, list, apply, pop, or drop stashed changes.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
    action: { type: 'enum', enum: ['save', 'list', 'apply', 'pop', 'drop'], description: "Stash action to perform" },
    message: { type: 'string', optional: true, description: "Stash message (for save action)" },
    stashRef: { type: 'string', optional: true, description: "Stash reference like 'stash@{0}' (for apply/pop/drop, defaults to stash@{0})" },
  },
    operationTypes: ['execute'],
    loader: () => import('./git_stash'),
  },
  {
    name: 'git_checkout',
    description: 'Restore files from a commit or branch, or discard working tree changes.',
    category: 'github',
    schemaDef: {
    absolutePath: { type: 'string', description: "Absolute path to the git repository (or any path inside it)" },
    files: { type: 'array', items: { type: 'string' }, description: "Absolute file paths to restore" },
    ref: { type: 'string', optional: true, description: "Commit SHA or branch to restore from (defaults to HEAD)" },
  },
    operationTypes: ['execute'],
    loader: () => import('./git_checkout'),
  },
];
