import type { ToolManifest } from '../registry';

export const rdctlToolManifests: ToolManifest[] = [
  {
    name: 'rdctl_extension',
    description: 'Manage extensions.',
    category: 'rdctl',
    schemaDef: {
    subcommand: { type: 'string', description: "Extension subcommand, e.g., install, uninstall, list" },
    args: { type: 'array', items: { type: 'string' }, optional: true, description: "Arguments for the subcommand" },
  },
    operationTypes: ['execute'],
    loader: () => import('./rdctl_extension'),
  },
  {
    name: 'rdctl_info',
    description: 'Return information about Sulla Desktop.',
    category: 'rdctl',
    schemaDef: {},
    operationTypes: ['read'],
    loader: () => import('./rdctl_info'),
  },
  {
    name: 'rdctl_list_settings',
    description: 'Lists the current settings.',
    category: 'rdctl',
    schemaDef: {},
    operationTypes: ['read'],
    loader: () => import('./rdctl_list_settings'),
  },
  {
    name: 'rdctl_reset',
    description: 'Reset Sulla Desktop.',
    category: 'rdctl',
    schemaDef: {},
    operationTypes: ['execute'],
    loader: () => import('./rdctl_reset'),
  },
  {
    name: 'rdctl_set',
    description: 'Update selected fields in the Rancher Desktop UI and restart the backend.',
    category: 'rdctl',
    schemaDef: {
    field: { type: 'string', description: "The field to update" },
    value: { type: 'string', description: "The value to set (as string)" },
  },
    operationTypes: ['update'],
    loader: () => import('./rdctl_set'),
  },
  {
    name: 'rdctl_shell',
    description: 'Run an interactive shell or a command in a Sulla Desktop-managed VM.',
    category: 'rdctl',
    schemaDef: {
    command: { type: 'string', optional: true, description: "Command to execute in the VM shell" },
  },
    operationTypes: ['execute'],
    loader: () => import('./rdctl_shell'),
  },
  {
    name: 'rdctl_shutdown',
    description: 'Shuts down the running Sulla Desktop application.',
    category: 'rdctl',
    schemaDef: {},
    operationTypes: ['execute'],
    loader: () => import('./rdctl_shutdown'),
  },
  {
    name: 'rdctl_snapshot',
    description: 'Manage Sulla Desktop snapshots.',
    category: 'rdctl',
    schemaDef: {
    subcommand: { type: 'string', description: "Snapshot subcommand, e.g., list, create, delete" },
    args: { type: 'array', items: { type: 'string' }, optional: true, description: "Arguments for the subcommand" },
  },
    operationTypes: ['execute'],
    loader: () => import('./rdctl_snapshot'),
  },
  {
    name: 'rdctl_start',
    description: 'Start up Sulla Desktop, or update its settings.',
    category: 'rdctl',
    schemaDef: {},
    operationTypes: ['execute'],
    loader: () => import('./rdctl_start'),
  },
  {
    name: 'rdctl_version',
    description: 'Shows the CLI version.',
    category: 'rdctl',
    schemaDef: {},
    operationTypes: ['read'],
    loader: () => import('./rdctl_version'),
  },
];
