import type { ToolManifest } from '../registry';

export const n8nToolManifests: ToolManifest[] = [
  {
    name: 'activate_workflow',
    description: 'Activate a workflow in n8n.',
    category: 'n8n',
    schemaDef: {
    id: { type: 'string', description: "Workflow ID" },
    versionId: { type: 'string', optional: true, description: "Version ID to activate" },
  },
    operationTypes: ['update', 'create'],
    loader: () => import('./activate_workflow'),
  },
  {
    name: 'archive_workflow',
    description: 'Archive or unarchive a workflow in n8n.',
    category: 'n8n',
    schemaDef: {
    id: { type: 'string', description: "Workflow ID" },
    action: {
      type: 'enum',
      enum: ['archive', 'unarchive'],
      optional: true,
      default: 'archive',
      description: "Archive behavior: archive (default) or unarchive.",
    },
  },
    operationTypes: ['update'],
    loader: () => import('./archive_workflow'),
  },
  {
    name: 'clone_workflow',
    description: 'Clone an existing n8n workflow into a new workflow name for safe experimentation.',
    category: 'n8n',
    schemaDef: {
    workflowId: { type: 'string', description: 'Source workflow ID to clone.' },
    newName: { type: 'string', description: 'Name for the cloned workflow.' },
  },
    operationTypes: ['read', 'create'],
    loader: () => import('./clone_workflow'),
  },
  {
    name: 'create_credential',
    description: 'Create a new credential in n8n.',
    category: 'n8n',
    schemaDef: {
    name: { type: 'string', description: "Credential name" },
    type: { type: 'string', description: "Credential type" },
    data: { type: 'string', description: "Credential data" },
    isResolvable: { type: 'boolean', optional: true, description: "Whether the credential is resolvable" },
  },
    operationTypes: ['create'],
    loader: () => import('./create_credential'),
  },
  {
    name: 'create_data_table',
    description: 'Create a new data table in n8n.',
    category: 'n8n',
    schemaDef: {
    name: { type: 'string', description: "Data table name" },
    columns: { type: 'array', items: {
      type: 'object',
      properties: {
        name: { type: 'string', description: "Column name" },
        type: { type: 'string', description: "Column type" },
      }
    }, description: "Data table columns" },
  },
    operationTypes: ['create'],
    loader: () => import('./create_data_table'),
  },
  {
    name: 'create_variable',
    description: 'Create a new variable in n8n.',
    category: 'n8n',
    schemaDef: {
    key: { type: 'string', description: "Variable key" },
    value: { type: 'string', description: "Variable value" },
    projectId: { type: 'string', nullable: true, optional: true, description: "Project ID or null for global" },
  },
    operationTypes: ['create'],
    loader: () => import('./create_variable'),
  },
  {
    name: 'create_workflow',
    description: "Create a new workflow in n8n. NOTE: For webhooks that return HTTP responses, always use responseMode: 'responseNode' with a Respond to Webhook node. The 'lastNode' mode is unreliable.",
    category: 'n8n',
    schemaDef: {
    name: { type: 'string', description: "Workflow name" },
    nodes: { type: 'array', items: { type: 'object' }, description: "Workflow nodes as n8n node objects." },
    connections: { type: 'object', description: "Workflow connections object keyed by source node name." },
    settings: { type: 'object', properties: {
      saveExecutionProgress: { type: 'boolean', optional: true },
      saveManualExecutions: { type: 'boolean', optional: true },
      saveDataErrorExecution: { type: 'string', optional: true },
      saveDataSuccessExecution: { type: 'enum', enum: ['none', 'all'], optional: true },
      executionTimeout: { type: 'number', optional: true },
      errorWorkflow: { type: 'string', optional: true },
      timezone: { type: 'string', optional: true },
      executionOrder: { type: 'string', optional: true },
      callerPolicy: { type: 'string', optional: true },
      callerIds: { type: 'string', optional: true },
      timeSavedPerExecution: { type: 'number', optional: true },
      availableInMCP: { type: 'boolean', optional: true },
    }, optional: true, default: {}, description: "Workflow settings" },
    shared: { type: 'array', items: { type: 'object' }, optional: true, description: "Shared users" },
    staticData: { type: 'object', optional: true, description: "Static data" },
  },
    operationTypes: ['create'],
    loader: () => import('./create_workflow'),
  },
  {
    name: 'deactivate_workflow',
    description: 'Deactivate a workflow in n8n.',
    category: 'n8n',
    schemaDef: {
    id: { type: 'string', description: "Workflow ID" },
  },
    operationTypes: ['update'],
    loader: () => import('./deactivate_workflow'),
  },
  {
    name: 'delete_workflow',
    description: 'Delete a workflow from n8n.',
    category: 'n8n',
    schemaDef: {
    id: { type: 'string', description: "Workflow ID" },
  },
    operationTypes: ['delete'],
    loader: () => import('./delete_workflow'),
  },
  {
    name: 'diagnose_webhook',
    description: 'Diagnose webhook readiness for a workflow by checking DB registration, workflow active state, endpoint response, and relevant n8n logs.',
    category: 'n8n',
    schemaDef: {
    workflowId: { type: 'string', description: 'Workflow ID to diagnose.' },
    container: { type: 'string', optional: true, default: 'sulla_n8n', description: 'Docker container name for n8n logs.' },
    endpointTimeoutMs: { type: 'number', optional: true, default: 15000, description: 'Timeout for endpoint probe request.' },
  },
    operationTypes: ['read', 'execute'],
    loader: () => import('./diagnose_webhook'),
  },
  {
    name: 'execute_n8n_workflow',
    description: 'Execute a workflow through a dedicated universal gateway workflow webhook, creating/activating the gateway if needed.',
    category: 'n8n',
    schemaDef: {
    workflowId: { type: 'string', description: 'Workflow ID.' },
    data: { type: 'object', optional: true, description: 'Optional run payload.' },
    mode: { type: 'string', optional: true, description: 'Execution mode: async (default) or sync.' },
    timeoutMs: { type: 'number', optional: true, description: 'Only for mode=sync: max wait time in milliseconds (default 30000).' },
  },
    operationTypes: ['execute'],
    loader: () => import('./execute_n8n_workflow'),
  },
  {
    name: 'get_credential',
    description: 'Get one n8n credential by ID.',
    category: 'n8n',
    schemaDef: {
    id: { type: 'string', description: 'Credential ID' },
  },
    operationTypes: ['read'],
    loader: () => import('./get_credential'),
  },
  {
    name: 'list_credentials',
    description: 'List n8n credentials with optional type filtering.',
    category: 'n8n',
    schemaDef: {
    type: { type: 'string', optional: true, description: "Optional credential type filter (e.g. twitterOAuth2Api)." },
    limit: { type: 'number', optional: true, description: "Maximum number of results" },
    cursor: { type: 'string', optional: true, description: "Cursor for pagination" },
  },
    operationTypes: ['read'],
    loader: () => import('./get_credentials'),
  },
  {
    name: 'get_current_user',
    description: 'Get current user info from n8n.',
    category: 'n8n',
    schemaDef: {},
    operationTypes: ['read'],
    loader: () => import('./get_current_user'),
  },
  {
    name: 'get_data_tables',
    description: 'Get all data tables from n8n with optional filtering.',
    category: 'n8n',
    schemaDef: {
    limit: { type: 'number', optional: true, description: "Maximum number of results" },
    cursor: { type: 'string', optional: true, description: "Cursor for pagination" },
    filter: { type: 'string', optional: true, description: "Filter criteria" },
    sortBy: { type: 'string', optional: true, description: "Sort field" },
  },
    operationTypes: ['read'],
    loader: () => import('./get_data_tables'),
  },
  {
    name: 'get_execution_log',
    description: 'Get full node-by-node execution output for a specific n8n execution ID, including per-node errors.',
    category: 'n8n',
    schemaDef: {
    executionId: { type: 'string', description: 'Execution ID to inspect.' },
  },
    operationTypes: ['read'],
    loader: () => import('./get_execution_log'),
  },
  {
    name: 'get_tags',
    description: 'Get all tags from n8n.',
    category: 'n8n',
    schemaDef: {},
    operationTypes: ['read'],
    loader: () => import('./get_tags'),
  },
  {
    name: 'get_template_categories',
    description: 'List all available n8n template categories from the public n8n template library.',
    category: 'n8n',
    schemaDef: {},
    operationTypes: ['read'],
    loader: () => import('./get_template_categories'),
  },
  {
    name: 'get_template_collections',
    description: 'Browse n8n template collections from the public n8n template library. Supports pagination.',
    category: 'n8n',
    schemaDef: {
    page: { type: 'number', optional: true, description: "Page number for pagination" },
    limit: { type: 'number', optional: true, description: "Number of results per page" },
  },
    operationTypes: ['read'],
    loader: () => import('./get_template_collections'),
  },
  {
    name: 'get_template_workflow',
    description: 'Get the details of a single n8n workflow template by its ID from the public n8n template library.',
    category: 'n8n',
    schemaDef: {
    id: { type: 'number', description: "Template workflow ID" },
  },
    operationTypes: ['read'],
    loader: () => import('./get_template_workflow'),
  },
  {
    name: 'get_variables',
    description: 'Get all variables from n8n with optional filtering.',
    category: 'n8n',
    schemaDef: {
    limit: { type: 'number', optional: true, description: "Maximum number of results" },
    cursor: { type: 'string', optional: true, description: "Cursor for pagination" },
    projectId: { type: 'string', optional: true, description: "Filter by project ID" },
    state: { type: 'enum', enum: ["empty"], optional: true, description: "Filter by state" },
  },
    operationTypes: ['read'],
    loader: () => import('./get_variables'),
  },
  {
    name: 'get_workflow',
    description: 'Get a specific workflow by ID from n8n.',
    category: 'n8n',
    schemaDef: {
    id: { type: 'string', description: "Workflow ID" },
    excludePinnedData: { type: 'boolean', optional: true, description: "Exclude pinned data" },
  },
    operationTypes: ['read'],
    loader: () => import('./get_workflow'),
  },
  {
    name: 'get_workflow_connections',
    description: 'Get only the workflow connections graph in a flattened, readable JSON shape.',
    category: 'n8n',
    schemaDef: {
    id: { type: 'string', description: 'Workflow ID' },
    excludePinnedData: { type: 'boolean', optional: true, description: 'Exclude pinned data' },
  },
    operationTypes: ['read'],
    loader: () => import('./get_workflow_connections'),
  },
  {
    name: 'get_workflow_node',
    description: 'Get a single node from a n8n workflow by nodeId or nodeName.',
    category: 'n8n',
    schemaDef: {
    workflowId: { type: 'string', description: 'Workflow ID' },
    nodeId: { type: 'string', optional: true, description: 'Node ID (preferred)' },
    nodeName: { type: 'string', optional: true, description: 'Node name (must be unique if used)' },
    excludePinnedData: { type: 'boolean', optional: true, description: 'Exclude pinned data from workflow fetch' },
  },
    operationTypes: ['read'],
    loader: () => import('./get_workflow_node'),
  },
  {
    name: 'get_workflow_node_list',
    description: 'Get a lightweight node list and connection edges for a workflow (without full node definitions).',
    category: 'n8n',
    schemaDef: {
    workflowId: { type: 'string', description: 'Workflow ID' },
    excludePinnedData: { type: 'boolean', optional: true, description: 'Exclude pinned data from workflow fetch' },
  },
    operationTypes: ['read'],
    loader: () => import('./get_workflow_node_list'),
  },
  {
    name: 'get_workflow_webhook_url',
    description: 'Get webhook trigger URLs for a workflow, including DB registration status and ready-to-use test commands.',
    category: 'n8n',
    schemaDef: {
    workflowId: { type: 'string', optional: true, description: 'Workflow ID (preferred).' },
    id: { type: 'string', optional: true, description: 'Workflow ID alias.' },
  },
    operationTypes: ['read', 'execute'],
    loader: () => import('./get_workflow_webhook_url'),
  },
  {
    name: 'get_workflows',
    description: 'Get all workflows from n8n with optional filtering.',
    category: 'n8n',
    schemaDef: {
    active: { type: 'boolean', optional: true, description: "Filter by active status" },
    tags: { type: 'string', optional: true, description: "Filter by tags" },
    name: { type: 'string', optional: true, description: "Filter by workflow name" },
    projectId: { type: 'string', optional: true, description: "Filter by project ID" },
    excludePinnedData: { type: 'boolean', optional: true, description: "Exclude pinned data" },
    limit: { type: 'number', optional: true, description: "Maximum number of results" },
    cursor: { type: 'string', optional: true, description: "Cursor for pagination" },
  },
    operationTypes: ['read'],
    loader: () => import('./get_workflows'),
  },
  {
    name: 'health_check',
    description: 'Check if n8n API is accessible and healthy.',
    category: 'n8n',
    schemaDef: {},
    operationTypes: ['read'],
    loader: () => import('./health_check'),
  },
  {
    name: 'list_workflow_executions',
    description: 'List recent executions for a workflow with a compact summary (status, start time, duration, error).',
    category: 'n8n',
    schemaDef: {
    workflowId: { type: 'string', description: 'Workflow ID' },
    limit: { type: 'number', optional: true, default: 20, description: 'Max executions to return (1-250).' },
  },
    operationTypes: ['read'],
    loader: () => import('./list_workflow_executions'),
  },
  {
    name: 'patch_workflow',
    description: 'Apply node and connection add/update/remove operations to an n8n workflow in one atomic update.',
    category: 'n8n',
    schemaDef: {
    workflowId: { type: 'string', description: 'Workflow ID' },
    operations: {
      type: 'array',
      description: 'Patch operations applied in sequence, then persisted in one atomic update. Node ops: target=node with op=add/update/remove. Connection ops: target=connection with op=add/remove, source (or connectionSource), connectionTarget, sourceOutputIndex/sourceIndex, targetInputIndex/targetIndex.',
      items: {
        type: 'object',
        properties: {
          target: { type: 'enum', enum: ['node', 'connection'], description: 'Operation target.' },
          op: { type: 'enum', enum: ['add', 'update', 'remove'], description: 'Operation verb.' },
          node: { type: 'object', description: 'For node add: full node object. For node update: optional full node object to replace/update complex nested fields reliably.' },
          nodeId: { type: 'string', description: 'For node update/remove: node ID selector.' },
          nodeName: { type: 'string', description: 'For node update/remove: node name selector.' },
          patch: { type: 'object', description: 'For node update: partial node patch object.' },
          source: { type: 'string', description: 'For connection add/remove: source node name (aliases: connectionSource, sourceNodeName).' },
          connectionTarget: { type: 'string', description: 'For connection add/remove: destination node name. You can also pass an object { node, index }.' },
          sourceOutputIndex: { type: 'number', description: 'For connection add/remove: source output index (alias: sourceIndex). Default 0.' },
          targetInputIndex: { type: 'number', description: 'For connection add/remove: destination input index (alias: targetIndex). Default 0.' },
        },
      },
    },
  },
    operationTypes: ['update'],
    loader: () => import('./patch_workflow'),
  },
  {
    name: 'restart_n8n_container',
    description: 'Restart the n8n Docker container, wait until healthy, and return webhook registration status.',
    category: 'n8n',
    schemaDef: {
    container: { type: 'string', optional: true, default: 'sulla_n8n', description: 'Docker container name or ID for n8n.' },
    timeoutMs: { type: 'number', optional: true, default: 120000, description: 'Max time to wait for readiness after restart.' },
    pollIntervalMs: { type: 'number', optional: true, default: 2000, description: 'Polling interval for readiness checks.' },
    includeLogs: { type: 'boolean', optional: true, default: true, description: 'Include recent webhook-related startup log lines in the response.' },
  },
    operationTypes: ['execute', 'update'],
    loader: () => import('./restart_n8n_container'),
  },
  {
    name: 'search_templates',
    description: 'Search n8n workflow templates from the public n8n template library. Supports keyword search, category filtering, node filtering, and pagination.',
    category: 'n8n',
    schemaDef: {
    search: { type: 'string', optional: true, description: "Keyword or phrase to search for" },
    category: { type: 'string', optional: true, description: "Category to filter templates by" },
    nodes: { type: 'string', optional: true, description: "Specific nodes used in the template to filter by" },
    page: { type: 'number', optional: true, description: "Page number for pagination" },
    limit: { type: 'number', optional: true, description: "Number of results per page" },
  },
    operationTypes: ['read'],
    loader: () => import('./search_templates'),
  },
  {
    name: 'set_workflow_active',
    description: 'Toggle a workflow active state on/off without doing a full workflow update.',
    category: 'n8n',
    schemaDef: {
    workflowId: { type: 'string', description: 'Workflow ID' },
    active: { type: 'boolean', description: 'true to activate, false to deactivate' },
    versionId: { type: 'string', optional: true, description: 'Optional version ID when activating.' },
  },
    operationTypes: ['update'],
    loader: () => import('./set_workflow_active'),
  },
  {
    name: 'update_workflow',
    description: "Update an existing workflow in n8n. NOTE: For webhooks that return HTTP responses, always use responseMode: 'responseNode' with a Respond to Webhook node. The 'lastNode' mode is unreliable.",
    category: 'n8n',
    schemaDef: {
    id: { type: 'string', description: "Workflow ID" },
    name: { type: 'string', optional: true, description: "Workflow name (defaults to existing workflow name if omitted)" },
    active: { type: 'boolean', optional: true, description: "Set workflow active state on update" },
    nodes: { type: 'array', items: { type: 'object' }, optional: true, description: "Workflow nodes as n8n node objects. Defaults to existing workflow nodes if omitted." },
    connections: { type: 'object', optional: true, description: "Workflow connections object keyed by source node name. Defaults to existing connections if omitted." },
    settings: { type: 'object', properties: {
      saveExecutionProgress: { type: 'boolean', optional: true },
      saveManualExecutions: { type: 'boolean', optional: true },
      saveDataErrorExecution: { type: 'string', optional: true },
      saveDataSuccessExecution: { type: 'enum', enum: ['none', 'all'], optional: true },
      executionTimeout: { type: 'number', optional: true },
      errorWorkflow: { type: 'string', optional: true },
      timezone: { type: 'string', optional: true },
      executionOrder: { type: 'string', optional: true },
      callerPolicy: { type: 'string', optional: true },
      callerIds: { type: 'string', optional: true },
      timeSavedPerExecution: { type: 'number', optional: true },
      availableInMCP: { type: 'boolean', optional: true },
    }, optional: true, description: "Workflow settings (defaults to existing workflow settings if omitted)" },
    shared: { type: 'array', items: { type: 'object' }, optional: true, description: "Shared users" },
    staticData: { type: 'object', optional: true, description: "Static data" },
  },
    operationTypes: ['update'],
    loader: () => import('./update_workflow'),
  },
  {
    name: 'validate_workflow',
    description: 'Validate an existing n8n workflow by ID and return graph health issues: floating nodes, missing credentials, broken connections, and nodes without type.',
    category: 'n8n',
    schemaDef: {
    workflowId: { type: 'string', description: 'Workflow ID to validate.' },
  },
    operationTypes: ['read', 'execute'],
    loader: () => import('./validate_workflow'),
  },
  {
    name: 'validate_workflow_payload',
    description: 'Validate an n8n workflow payload (nodes/connections/settings) before create/update.',
    category: 'n8n',
    schemaDef: {
    name: { type: 'string', description: "Workflow name" },
    nodes: { type: 'array', items: { type: 'object' }, description: "Workflow nodes as n8n node objects." },
    connections: { type: 'object', description: "Workflow connections object keyed by source node name." },
    settings: { type: 'object', optional: true, default: {}, description: "Workflow settings object." },
    shared: { type: 'array', items: { type: 'object' }, optional: true, description: "Shared users array." },
    staticData: { type: 'object', optional: true, description: "Workflow staticData object." },
    checkConnection: { type: 'boolean', optional: true, default: true, description: "When true, also checks n8n API health connectivity." },
  },
    operationTypes: ['execute'],
    loader: () => import('./validate_workflow_payload'),
  },
];
